### ISSUE TITLE
Can't run DvsGestures example

### ISSUE THREAD

**Issue by GiorgosAlexakis** [nmi-lab/decolle-public#20]
**python train_lenet_decolle.py --params_file=parameters/params_dvsgestures_torchneuromorphic.yml**
Saving results to logs/train_lenet_decolle/default/Jul17_18-05-01_george-System-Product-Name
/home/george/.local/lib/python3.8/site-packages/decolle-0.1-py3.8.egg/decolle/utils.py:122: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
The following files did not exist, will attempt download:
data/dvsgesture/raw
Using downloaded and verified file: data/dvsgesture/DvsGesture.tar.gz
Extracting data/dvsgesture/DvsGesture.tar.gz to data/dvsgesture/
Traceback (most recent call last):
  File "train_lenet_decolle.py", line 39, in <module>
    gen_train, gen_test = create_data(chunk_size_train=params['chunk_size_train'],
  File "/home/george/.local/lib/python3.8/site-packages/torchneuromorphic-0.3.4-py3.8.egg/torchneuromorphic/dvs_gestures/dvsgestures_dataloaders.py", line 166, in create_dataloader
  File "/home/george/.local/lib/python3.8/site-packages/torchneuromorphic-0.3.4-py3.8.egg/torchneuromorphic/dvs_gestures/dvsgestures_dataloaders.py", line 59, in __init__
  File "/home/george/.local/lib/python3.8/site-packages/torchneuromorphic-0.3.4-py3.8.egg/torchneuromorphic/neuromorphic_dataset.py", line 104, in __init__
  File "/home/george/.local/lib/python3.8/site-packages/torchneuromorphic-0.3.4-py3.8.egg/torchneuromorphic/dvs_gestures/dvsgestures_dataloaders.py", line 76, in create_hdf5
  File "/home/george/.local/lib/python3.8/site-packages/torchneuromorphic-0.3.4-py3.8.egg/torchneuromorphic/dvs_gestures/create_hdf5.py", line 23, in create_events_hdf5
  File "/home/george/.local/lib/python3.8/site-packages/torchneuromorphic-0.3.4-py3.8.egg/torchneuromorphic/dvs_gestures/create_hdf5.py", line 72, in gather_aedat
**FileNotFoundError: DVS Gestures Dataset not found, looked at: data/dvsgesture/raw**

**Comment by GiorgosAlexakis** [comment]
I figured the files had to be unzipped in the raw folder, but after that my pc completely freezes while running the script.

**Comment by weinman** [comment]
@Looper2074 Have you determined what line the script may be stuck at? Assuming you got the files unzipped to the right place, it's perhaps somewhere within `create_events_hdf5`([here](https://github.com/nmi-lab/torchneuromorphic/blob/8a396917028b7fca091c91e8cad28ccebe729367/torchneuromorphic/dvs_gestures/create_hdf5.py#L22)). You might try stepping through the code with pdb to figure out which part may be causing the trouble. 

(It doesn't necessarily help you solve the problem, but I will say I was able to get this to run myself, so I can vouch that once you've downloaded the data it *does* work, even if it might take a while to process.)

**Comment by eneftci** [comment]
> I figured the files had to be unzipped in the raw folder, but after that my pc completely freezes while running the script.

The script constructs an hdf5 version of the dataset which may take a while. This is a torchneuromorphic issue though.
