### ISSUE TITLE
Issues when running a demo

### ISSUE THREAD

**Issue by rachmadvwp** [nmi-lab/decolle-public#7]
Hi @eneftci,
I'd like to ask, how to solve the issue that I found when running the given demo.
Following is the log:

```
(decolle) user@user-VBox:/media/user/VBoxShared/decolle-public/scripts$ python train_lenet_decolle.py
Saving results to logs/train_lenet_decolle/default/Dec13_04-24-38_user-VBox
/home/user/.local/lib/python3.9/site-packages/decolle-0.1-py3.9.egg/decolle/utils.py:137: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
The following files did not exist, will attempt download:
data/nmnist/Train
data/nmnist/Test
Traceback (most recent call last):
  File "/media/user/VBoxShared/decolle-public/scripts/train_lenet_decolle.py", line 39, in <module>
    gen_train, gen_test = create_data(chunk_size_train=params['chunk_size_train'],
  File "/home/user/.local/lib/python3.9/site-packages/torchneuromorphic-0.3.1-py3.9.egg/torchneuromorphic/nmnist/nmnist_dataloaders.py", line 180, in create_dataloader
  File "/home/user/.local/lib/python3.9/site-packages/torchneuromorphic-0.3.1-py3.9.egg/torchneuromorphic/nmnist/nmnist_dataloaders.py", line 153, in create_datasets
  File "/home/user/.local/lib/python3.9/site-packages/torchneuromorphic-0.3.1-py3.9.egg/torchneuromorphic/nmnist/nmnist_dataloaders.py", line 59, in __init__
  File "/home/user/.local/lib/python3.9/site-packages/torchneuromorphic-0.3.1-py3.9.egg/torchneuromorphic/neuromorphic_dataset.py", line 103, in __init__
  File "/home/user/.local/lib/python3.9/site-packages/torchneuromorphic-0.3.1-py3.9.egg/torchneuromorphic/nmnist/nmnist_dataloaders.py", line 81, in download
  File "/home/user/.local/lib/python3.9/site-packages/torchneuromorphic-0.3.1-py3.9.egg/torchneuromorphic/neuromorphic_dataset.py", line 171, in download
  File "/home/user/.local/lib/python3.9/site-packages/torchneuromorphic-0.3.1-py3.9.egg/torchneuromorphic/neuromorphic_dataset.py", line 83, in download_and_extract_archive
  File "/home/user/.local/lib/python3.9/site-packages/torchneuromorphic-0.3.1-py3.9.egg/torchneuromorphic/neuromorphic_dataset.py", line 45, in download_url
ModuleNotFoundError: No module named 'requests'

```

Thanks in advance and Best Regards

**Comment by rachmadvwp** [comment]
I've solved this, so I'll close the thread.
